let products = [
  {
    id: 1,
    url: "product.html?id=1",
    title: "Rounded Red Hat",
    image: "images/products/product10.png",
    oldPrice: 26,
    price: 150,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "minimog",
    count: 10,
    bestSeller: true,
    newArrival: true,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 2,
    url: "product.html?id=2",
    title: "Long-seleeve Coat",
    image: "images/products/product11.png",
    price: 106,
    colors: [
      {
        name: "#ebe6db",
        selected: true,
      },
      {
        name: "#c1e1c1",
        selected: false,
      },
    ],
    isSold: true,
    brand: "retrolie",
    count: 0,
    bestSeller: true,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 3,
    url: "product.html?id=3",
    title: "Linen-blend Shirt",
    image: "images/products/product12.png",
    oldPrice: 50,
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "brook",
    count: 12,
    bestSeller: true,
    newArrival: true,
    category: "women-accessories",
    sizes: ["m", "l", "2xl"],
  },
  {
    id: 4,
    url: "product.html?id=4",
    title: "Rounded Red Hat",
    image: "images/products/product13.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "learts",
    count: 20,
    bestSeller: true,
    newArrival: false,
    category: "women-accessories",
    sizes: ["s", "m", "l", "xl", "2xl"],
  },
  {
    id: 21,
    url: "product.html?id=21",
    title: "Long-seleeve Coat",
    image: "images/products/product14.png",
    price: 106,
    colors: [
      {
        name: "#ebe6db",
        selected: true,
      },
      {
        name: "#c1e1c1",
        selected: false,
      },
    ],
    isSold: true,
    brand: "vagabond",
    count: 0,
    bestSeller: true,
    newArrival: true,
    category: "men-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 5,
    url: "product.html?id=5",
    title: "Linen-blend Shirt",
    image: "images/products/product15.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 50,
    bestSeller: false,
    newArrival: false,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 6,
    url: "product.html?id=6",
    title: "Rounded Red Hat",
    image: "images/products/product15.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "brook",
    count: 5,
    bestSeller: false,
    newArrival: true,
    category: "men-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 7,
    url: "product.html?id=7",
    title: "Long-seleeve Coat",
    image: "images/products/product17.png",
    price: 106,
    colors: [
      {
        name: "#ebe6db",
        selected: true,
      },
      {
        name: "#c1e1c1",
        selected: false,
      },
    ],
    isSold: true,
    brand: "abby",
    count: 0,
    bestSeller: true,
    newArrival: false,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 8,
    url: "product.html?id=8",
    title: "Linen-blend Shirt",
    image: "images/products/product5.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "minimog",
    count: 20,
    bestSeller: false,
    newArrival: true,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 9,
    url: "product.html?id=9",
    title: "Linen-blend Shirt",
    image: "images/products/product5.png",
    oldPrice: 25,
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 10,
    bestSeller: false,
    newArrival: true,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 10,
    url: "product.html?id=10",
    title: "Linen-blend Shirt",
    image: "images/products/product4.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 4,
    bestSeller: true,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 11,
    url: "product.html?id=11",
    title: "Linen-blend Shirt",
    image: "images/products/product5.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 1,
    bestSeller: true,
    newArrival: false,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 12,
    url: "product.html?id=12",
    title: "Linen-blend Shirt",
    image: "images/products/product5.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 20,
    bestSeller: true,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 13,
    url: "product.html?id=13",
    title: "Rounded Red Hat",
    image: "images/products/product10.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 0,
    bestSeller: false,
    newArrival: false,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 14,
    url: "product.html?id=14",
    title: "Long-seleeve Coat",
    image: "images/products/product11.png",
    price: 106,
    colors: [
      {
        name: "#ebe6db",
        selected: true,
      },
      {
        name: "#c1e1c1",
        selected: false,
      },
    ],
    isSold: true,
    brand: "abby",
    count: 0,
    bestSeller: false,
    newArrival: false,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 15,
    url: "product.html?id=15",
    title: "Linen-blend Shirt",
    image: "images/products/product12.png",
    oldPrice: 30,
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 11,
    bestSeller: false,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 16,
    url: "product.html?id=16",
    title: "Rounded Red Hat",
    image: "images/products/product13.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 10,
    bestSeller: true,
    newArrival: true,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 17,
    url: "product.html?id=17",
    title: "Rounded Red Hat",
    image: "images/products/product10.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 10,
    bestSeller: false,
    newArrival: false,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 18,
    url: "product.html?id=18",
    title: "Long-seleeve Coat",
    image: "images/products/product11.png",
    oldPrice: 200,
    price: 106,
    colors: [
      {
        name: "#ebe6db",
        selected: true,
      },
      {
        name: "#c1e1c1",
        selected: false,
      },
    ],
    isSold: true,
    brand: "abby",
    count: 1,
    bestSeller: true,
    newArrival: true,
    category: "women-fashion",
    sizes: ["s", "m", "l"],
  },
  {
    id: 19,
    url: "product.html?id=19",
    title: "Linen-blend Shirt",
    image: "images/products/product12.png",
    price: 17,
    colors: [
      {
        name: "#8db4d2",
        selected: true,
      },
      {
        name: "#ffd1dc",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 0,
    bestSeller: false,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
  {
    id: 20,
    url: "product.html?id=20",
    title: "Rounded Red Hat",
    image: "images/products/product13.png",
    price: 8,
    colors: [
      {
        name: "#ff6c6c",
        selected: true,
      },
      {
        name: "#fff629",
        selected: false,
      },
    ],
    isSold: false,
    brand: "abby",
    count: 2,
    bestSeller: true,
    newArrival: true,
    category: "women-accessories",
    sizes: ["s", "m", "l"],
  },
];

localStorage.setItem("products", JSON.stringify(products));
